### PR TITLE
Flashcards scrolling, removal restrictions and tests

### PR DESCRIPTION
**Pull request by williammartinez10**
#### What was done:

* Ensure that the user is also able to scroll through the flashcards overview screen on the WebApp, and polished flashcards overview screen layout to improve content and component visibility. 
* Added restrictions for flashcard management, in order to ensure that at least one study set is available for a pet to exist. Also, made sure that study set must also have at least one flashcard inside it.
* Prevented removal of the last remaining flashcard in a study set, if there aren't more study sets available.
* Fixed “remove all” functionality on WebApp and made sure it aligned with the new removal restrictions
* Created new TDD tests for cases that didn’t have any (scrolling and remove all)
* Updated creation and removal of flashcards TDD tests after the made changes

#### How to run tests?
- Run ```npm run test-jest```
    
    #### What to look out for?
    - New *scroll* test
    - Updated flashcard removal test showcasing restrictions 
        - Try removing first flashcard when it is the only one available and it is not possible
        - Added a second flashcard to the available study set, try removing it, and it is successful
    - Updated test allowing creation and removal after layout changes
    - New *remove all* test

### CODE REVIEW

**Comment by PinkSylvie** [comment]
image
image
I wasn't able to run the tests but it could be an issue on my side, happened when I was trying to run other tests as well. @irsaris does it happen on your side as well. If it runs on her then is on issue on my side and should be good to go.

**Comment by irsaris** [comment]
have these tests also been added to documentation?

**Comment by williammartinez10** [comment]
Yes

**Comment by PinkSylvie** [comment]
What section? You don't appear in the change log

**Comment by williammartinez10** [comment]
Section 4.1.4

**Comment by williammartinez10** [comment]
It should now appear in the change log

**Comment by williammartinez10** [comment]
Done

**Comment by PinkSylvie** [comment]
The eat tests seem to have some errors as show in the picture

**Comment by williammartinez10** [comment]
Yeah, I believe that is part of another issue that may be assigned to someone else. I could create a separate file named ```flashcardsPage.test.js```, and move all the tests that belong to the flashcards page over there, to get rid of that. However, those failed tests will still show up because that wasn't part of the issues i was supposed to work on.

**Comment by PinkSylvie** [comment]
Explain that then in the image description because fail tests with errors don't look good

**Comment by williammartinez10** [comment]
Fixed it

**Comment by PinkSylvie** [comment]
Tried it out and it might be a small bug but I tried out the removal and while remove all didnt do anything when I pressed remove it removed all the question sets
image

**Comment by PinkSylvie** [comment]
Also please add the information regarding the tests you ran to the milestone 3 documentation

**Comment by williammartinez10** [comment]
I believe the issue is now corrected. The information related to the tests has been added to the milestone 3 documentation under the TDD section.

**Review by gabrielpadilla7 — APPROVED** [review]
image

All tests pass and everything seems to be in order! Here's a little tip, when running the test, you don't need to run the entire test suite by typing "npm run test-jest", if you instead use npx jest and the name of the test (for example in this case "npx jest flashcardsPage.test.js", it'll only run that test suite, speeding up the process since you can now only test that specific test suite.

**Review by PinkSylvie — APPROVED** [review]
My laptop still gives me issues running the tests but if it ran for @gabrielpadilla7 and on yours I know the issue is solely on my side so its good to merge. Make sure the test is documented

**Comment by williammartinez10** [comment]
Merge conflicts were solved, and documentation has been updated.

**Pull request merged**
