### PR TITLE
Difficulty add

### PR DESCRIPTION
**Pull request by bally7301**
ya lo prove y funciona en los minijuegos de flashcard este es de task #277

### CODE REVIEW

**Comment by PinkSylvie** [comment]
image
image
image
I saw these while I was trying to run your branch. Is the first time I've seen the loading questions and no matter how much I wait nothing happens. I still see the difficulty selection in the bath minigame and I dont see the difficulty selected for the pet reflected in the stats

**Review by gabrielpadilla7 — CHANGES_REQUESTED** [review]
image

No matter how much you wait, the questions never load. It's like the async storage is trying to look for them but can't find them and doesn't have a way to return an error code/timeout. 


In any case, it looks like this code is not working for the minigame.

**Comment by gabrielpadilla7** [comment]
Considerin this PR has many merge conflicts, it makes me believe that the branch was created from a much earlier version of the main branch.

**Comment by bally7301** [comment]
Revisen si creando el Pet y después creando elegir la dificultad y después de entrar al minigame funciona porque está raro ya que ayer me funcionó bien y yo le e echo pull a todo desde ayer

**Pull request closed without merging**
