### PR TITLE
Care Difficulty

### PR DESCRIPTION
**Pull request by Elielh17**
Implemented algorithm that depending on the difficulty sets the number of questions to answer to a certain number. Easy - 1/3 of questions (3 questions), Intermediate - 2/3 of questions (6 questions) and Hard - 3/3 questions (9 questions). The questions are chosen randomly from the array of questions. If there are less than 9 then the number of questions is sliced case "easy": fraction = 1 / 3, case "medium": fraction = 2 / 3, case "hard": fraction = 1

Screenshot 2024-03-19 171006

Screenshot 2024-03-19 171111

Screenshot 2024-03-19 171032

Screenshot 2024-03-19 171124

### CODE REVIEW

**Comment by Elielh17** [comment]
Merge conflicts were solved

**Comment by PinkSylvie** [comment]
Por favor arregla los conflicts, intente probarlo creando una nueva mascota pero no se reflejaba la dificultad en las preguntas

**Comment by Elielh17** [comment]
> Por favor arregla los conflicts, intente probarlo creando una nueva mascota pero no se reflejaba la dificultad en las preguntas

Right now data permanency of the pet is not implemented. So there isnt a way to access the pet difficulty from the minigames. I will add a temporary button to change difficulty so it can be tested.

**Comment by Elielh17** [comment]
Added a temporary picker to change the difficulty.

image

image

**Comment by PinkSylvie** [comment]
Lo intente probar pero a Expo le esta dando un yeyo por Picker

**Comment by PinkSylvie** [comment]
No me deja jugar los minijuegos ahora

**Comment by Elielh17** [comment]
Changed the picker to 3 buttons to change difficulty

image

image

**Review by gabrielpadilla7 — CHANGES_REQUESTED** [review]
While it does work, I found two things. 

1. image
For the mini game section, the game has shifted, causing it to get cut off from the screen. Adding a scrollbar can fix this, or moving the difficulty at the bottom to prioritize the game itself

2. 
image
My eat section works, however the Hunger and Happiness do not look like the pictures sent at the beginning of this issue.
3. 
image
Warnings appear about the font in the game section

**Review by CaribbeanCool — APPROVED** [review]

**Comment by Elielh17** [comment]
> While it does work, I found two things. 
> 
> 
> 
> 1. image
> 
> For the mini game section, the game has shifted, causing it to get cut off from the screen. Adding a scrollbar can fix this, or moving the difficulty at the bottom to prioritize the game itself
> 
> 
> 
> 2. 
> 
> image
> 
> My eat section works, however the Hunger and Happiness do not look like the pictures sent at the beginning of this issue.
> 
> 3. 
> 
> image
> 
> Warnings appear about the font in the game section
> 
> 
> 
> 
> 
> 

The buttons are temporary and were put there for testing of the difficulty.

**Review by FrHend-Raul — COMMENTED** [review]
I know this buttons are temporary, but they push too much the minigames and since there are no scroll then it is hard to play the minigame. I would suggest changing size of the buttons, and if you can do them side by side intead of below then it would not take as much space

**Comment by Elielh17** [comment]
> I know this buttons are temporary, but they push too much the minigames and since there are no scroll then it is hard to play the minigame. I would suggest changing size of the buttons, and if you can do them side by side intead of below then it would not take as much space

I removed the styling of the buttons. Now all buttons can be seen.

**Review by FrHend-Raul — APPROVED** [review]
Ok, the buttons are better and you can play the minigames even on phone. You have an issue with the fonts in the game page, but that one has been worked on another pull request. I think that is ready for merge.

**Pull request merged**
