### PR TITLE
Implemented Hunger and Happiness hourly changes

### PR DESCRIPTION
**Pull request by JConcepcion01**

### CODE REVIEW

**Review by CaribbeanCool — COMMENTED** [review]
It runs on my end. LGTM 👍

**Review by CaribbeanCool — APPROVED** [review]

**Comment by PinkSylvie** [comment]
I tried testing it out and waited with the app open for an hour and a bit but didn't see any change in the pet stat screen

**Comment by PinkSylvie** [comment]
@JConcepcion01

**Comment by JConcepcion01** [comment]
@PinkSylvie 

you can try reducing the time frame for debugging. It worked for me on my side at least

**Comment by PinkSylvie** [comment]
Also how does the time work? Because even if the hunger is supposed to increase every hour it seems as if you have it to increase every 10 since you have the same timelapse as the happiness. And I think decreasing one tab of happiness every 10 hours is too slow. Is like taking one percent off every 10 hours. I think a decrease of 10 every hour will make it so that it would take 10 hours for the tab to reach 0.
image

**Comment by JConcepcion01** [comment]
Time is kind of simulated with the “ticks” of the program. And I do indeed think the time is a bit too long aswell ^^’ but I was just following the specifications of the task ^^’

**Comment by PinkSylvie** [comment]
According to the task I had mentioned a happiness decrease of 10 every hour. Not 1 happiness decrease every 10 hours

**Comment by JConcepcion01** [comment]
Ohh. My bad, I got it mixed up then. I can change it if you wish then

**Comment by PinkSylvie** [comment]
Please do change it, but I tried it out doing the 5 second thing you said for testing and it worked great! So I think once the change is done and you ensure there are no conflicts, you can merge the branch into main :)

**Comment by JConcepcion01** [comment]
Awesome! Will do so right now!

**Comment by JConcepcion01** [comment]
Changes are now done. I will do the merge pull request and close the task if that's okay. I'll wait for confirmation

**Comment by PinkSylvie** [comment]
Sounds great! Completely fine by me 👍

**Pull request merged**
