### PR TITLE
Difficulty adjustment & testing

### PR DESCRIPTION
**Pull request by Elielh17**
Conducted integration testing on the difficulty adjustment feature within the minigames to verify its interaction with other game components and future integration with local storage. The difficulty of the minigames will be changed using the pet data that will be stored on the local storage, when the issue #277 is completed. Some code refactoring of the Eating minigame file was done, to make it follow the same structure as the other minigames.

### CODE REVIEW

**Comment by PinkSylvie** [comment]
How do I run this so I can see the tests you implemented?

**Comment by Elielh17** [comment]
> How do I run this so I can see the tests you implemented?

With the command: npm run test-jest

**Comment by PinkSylvie** [comment]
image
Got this error when running it which is new, but also got a similar error I had seen when running other tests which seems to be an issue with my laptop and not the tests themselves: 
image
@irsaris do you get this error?

**Comment by Elielh17** [comment]
> image Got this error when running it which is new, but also got a similar error I had seen when running other tests which seems to be an issue with my laptop and not the tests themselves: image @irsaris do you get this error?

When the command is run, all the tests that are created are run, if you want to see the tests created for this pull request, search for the tests BathDifficultyTest.js, EatingminigameTest.js, MinigameTest.js.

image

**Comment by PinkSylvie** [comment]
They don't pass on my side which could be an issue with my laptop

**Comment by irsaris** [comment]
> image Got this error when running it which is new, but also got a similar error I had seen when running other tests which seems to be an issue with my laptop and not the tests themselves: image @irsaris do you get this error?

sorry for the late reply, yes

**Review by irsaris — APPROVED** [review]

**Pull request merged**
