### PR TITLE
Added property based testing to the minigame component

### PR DESCRIPTION
**Pull request by AnthonyMed13**
Implemented a property based test for the minigame component. This includes test to ensure that the number of questions given is inline with what we expected, generating values that are outside of our expected values and ensuring that even if other inputs are given the  test can still detect them. This uses mocks of the expected data to function.

### CODE REVIEW

**Comment by PinkSylvie** [comment]
Hello! Could you explain how to run these tests and what we should be looking out for?

**Comment by AnthonyMed13** [comment]
> Hello! Could you explain how to run these tests and what we should be looking out for?

I set it up to be able to run when you run "npm run test-jest" if it were to fail it would output the rendered page. If it doesnt fail it just says passed like this:
image

**Review by williammartinez10 — APPROVED** [review]

**Comment by PinkSylvie** [comment]
image
I was able to see the minigame tests pass, but had some issues with others. But that probably is because my loptop doesnt take nicely the firefox popups.
image
image

**Review by PinkSylvie — APPROVED** [review]
Please fix the merge conflicts so that you can merge, I believe the failed tests are due to my laptop having issues with the firefox pop ups which had happened on a previous task as well when I ran its tests.

**Pull request merged**
