### PR TITLE
Automated property testing 

### LINKED ISSUE #262: [Lecture Topic Task] Property Based Testing Automation
Following up on task #255, automate the Property Based Tests so that they run the whole test suite with as little setup as possible.

Please review with the professor on how he would like for the automation to be done.
To complete:
Explain how to run the automated tests and show them running and the results they generate

### PR DESCRIPTION
**Pull request by JConcepcion01**
Added automated property testing. Closes #262. Further testing required

### CODE REVIEW

**Comment by JConcepcion01** [comment]
Automated Testers now work, when verified, please merge.

**Comment by PinkSylvie** [comment]
How do you test run these tests?

**Comment by JConcepcion01** [comment]
@PinkSylvie It's an automated test, like github metrics, the only way to manually test it is with the "npx jest minigame.test.js" but that was basically from the task 255 that the other person did. So unless you push and pull, You cant really manually test it. That's why I had to do multiple push and pulls, to be able to test it and see what errors github threw at me when it finished analyzing it alongside checking for merge conflicts.

**Comment by PinkSylvie** [comment]
Did you add to the documentation about this?

**Comment by PinkSylvie** [comment]
Also please fix the conflicts

**Comment by JConcepcion01** [comment]
@PinkSylvie I'll solve the merge conflicts in a bit. About the documentation, didnt know about that. I see A whole section of a bunch of subs-sections that all go about testing. Any specific place you wish for me to put it or do I choose any? Cuz Im honestly not fully sure

**Comment by PinkSylvie** [comment]
I think a new section under section 4 will be needed. Make sure to add the section in the table of contents as well

**Comment by JConcepcion01** [comment]
@PinkSylvie I got a question, someone just brought up to me that task #264 exists. Should I still add it or is it up to the person assigned to that task? I dont mind adding it, just want to make sure.

**Comment by PinkSylvie** [comment]
Keep it in bay just in case so since @bally7301 should look onto what you did to be able to complete it. I think at the very least you should add an explanation of the automation while @bally7301 summarizes the results and conclusions of the feedback. Also please fix the conflicts, after this is done it should be fine to merge

**Review by PinkSylvie — APPROVED** [review]
It ran nicely, great job! Should be ready to merge

**Comment by JConcepcion01** [comment]
Solved the merge conflicts. All good to merge with main now

**Pull request merged**
