### PR TITLE
FLASHCARD TEAM - Overview and FlashCard placeholder

### PR DESCRIPTION
**Pull request by CaribbeanCool**
# Description
This branch holds the functionalities of #95 and #36, #37, #38.
This branch displays the overview of flashcards and the ability to create a flashcard (very basic functionality)

### CODE REVIEW

**Comment by CaribbeanCool** [comment]
@FrHend-Raul @PinkSylvie Is this branch ready to merge?

**Comment by PinkSylvie** [comment]
Haven't been able to run it

**Comment by CaribbeanCool** [comment]
# Overview page
image
# Creation of FlashCard
image
# FlashCard with answer revealed
image

**Comment by CaribbeanCool** [comment]
Can I merge @PinkSylvie ?

**Comment by PinkSylvie** [comment]
> Can I merge @PinkSylvie ?

I haven't been able to run the app yet on my side

**Pull request merged**
