### PR TITLE
`happiness` aspect

### LINKED ISSUE #169: Implement and connect `happiness` aspect to the Pet
# Description
When feeding and cleaning the Pet, it gains happiness, which is an aspect of its survivability, and we have to connect this aspect to the Pet itself.
# Points
Tentative(Difficulty 3 x Priority 4)

### PR DESCRIPTION
**Pull request by CaribbeanCool**
# Description
This branch it up to date and contains the `happiness` aspect of the Pet accessible and with data permanence, and it's connected to the `Eat` page and minigame.

close #169

### CODE REVIEW

**Comment by CaribbeanCool** [comment]
@PinkSylvie  @irsaris Here is my task. Please make sure it runs on your end before merging.

**Comment by PinkSylvie** [comment]
I'll check it out ASAP

**Comment by PinkSylvie** [comment]
I ran it and tried it but it doesn't seem to affect the happiness and hunger in the stats screen

**Comment by PinkSylvie** [comment]
@CaribbeanCool

**Comment by CaribbeanCool** [comment]
> @CaribbeanCool

Yeah, no añadi eso. lo hago ahora

**Comment by PinkSylvie** [comment]
I tried it out and neither the happiness nor the hunger are affected by the eat mini game in the stat screen

**Comment by PinkSylvie** [comment]
@CaribbeanCool

**Comment by CaribbeanCool** [comment]
> @CaribbeanCool

Weird because when I use it on iOS, when I finish a minigame(new happiness is 133), it will show on `Stats.js` that I have 133% Happiness, and hunger isn't my task

**Comment by PinkSylvie** [comment]
I tested it on IOS. I even decreased the happiness manually from the default value it had so I could watch it increase after playing but didn't see any change in the stat screen

**Comment by CaribbeanCool** [comment]
> I tested it on IOS. I even decreased the happiness manually from the default value it had so I could watch it increase after playing but didn't see any change in the stat screen

image
image
# After a refresh:
image
image

**Comment by PinkSylvie** [comment]
Why is happiness going above 100%? But I can see the changes now being applied onto the stat screen. I just think that if happiness is full it shouldn't get any fuller so that the pet follows the schedule that if it gets no care in 10 hours its happiness will decrease completely to 0. Allowing the happiness to go above 100% allows the user to create a buffer against that.

**Comment by CaribbeanCool** [comment]
@PinkSylvie Ya puse el cap al happiness.

**Review by irsaris — APPROVED** [review]

**Review by FrHend-Raul — APPROVED** [review]
For me, it is ready for merge

**Pull request merged**
