### PR TITLE
EmotionBDD

### PR DESCRIPTION
**Pull request by benjaminCMD**
I still havent been able to test these cases since cucumber doesnt want to work for me

### CODE REVIEW

**Comment by irsaris** [comment]
#270

**Comment by gabrielpadilla7** [comment]
@benjaminCMD How am i supposed to run these partifular tests/scenarios?

**Comment by benjaminCMD** [comment]
Well, that's the issue I'm having so far. You're supposed install cucumber by typing "npm install --save-dev @cucumber/cucumber" in the terminal, and then typing "npx cucumber-js" to run the test cases, but I havent been able to connect to the framework properly.

**Comment by gabrielpadilla7** [comment]
I see, do let me know as quick as you can when they're up and running so the merge can be done

**Comment by benjaminCMD** [comment]
image
I was able to run the code using npx cucumber-js petEmotion.feature. These are my results @gabrielpadilla7

**Pull request closed without merging**
