### PR TITLE
Health hunger balance

### LINKED ISSUE #273: Balance happiness increases and hunger increases
Balance happiness increases and hunger increases so that it doesn't automatically raise a pets happiness to a 100 just by getting all answers correct. We want the students to study a decent amount of time.
Medium Priority Medium Difficulty=4*4

### PR DESCRIPTION
**Pull request by CaribbeanCool**
This PR contains the code that balances the values of happiness and hunger when playing the minigames. The calculations can change. I just put a placeholder.

### CODE REVIEW

**Comment by CaribbeanCool** [comment]
@PinkSylvie
# Case 1: Eat minigame (Hard difficulty)
Screenshot 2024-04-25 230542
Screenshot 2024-04-25 230550
# Case 2: Game page minigame (easy difficulty)
Screenshot 2024-04-25 230945
Screenshot 2024-04-25 230951

**Comment by CaribbeanCool** [comment]
@PinkSylvie
# Case 3: Bath Game (Easy difficulty)
image
image

**Comment by PinkSylvie** [comment]
image
The balance isnt reflected in the stats or in the score so I cant see the balance actually happening

**Comment by gabrielpadilla7** [comment]
@PinkSylvie Is this PR ready for merging or do changes need to be made? I ask becuase of your last comment

**Comment by PinkSylvie** [comment]
Since last time I tried it I havent seen the changes be reflected

**Comment by gabrielpadilla7** [comment]
> Since last time I tried it I havent seen the changes be reflected

Then I won't merge it in the meantime

**Comment by CaribbeanCool** [comment]
@PinkSylvie The logic for the hunger and happiness balance is there. Still, I can't move forward since there are problems with AsyncStorage (specifically showing the new increments properly in the result screen).

**Comment by PinkSylvie** [comment]
I see no evidence of the balance, no logs. no change, no anything. Only the code

**Comment by CaribbeanCool** [comment]
@PinkSylvie What about the photos above? The three cases show the result screen and the console logs of the new calculations for these games

**Comment by PinkSylvie** [comment]
Doesnt appear on my side

**Comment by gabrielpadilla7** [comment]
@CaribbeanCool How do I go about testing this PR? As in, what steps should i take in order to test this out and give it an approval?

**Review by PinkSylvie — APPROVED** [review]
The balance works great! Great job!

**Pull request merged**
