### PR TITLE
Sound effects

### LINKED ISSUE #243: Interaction Sounds
Implement interaction sounds for the application. 

Suggested prio and diff:
Difficulty: 5
Priority: 3

### PR DESCRIPTION
**Pull request by gabrielpadilla7**
Implemented sound effects. Closes #243 

NOTE: PLEASE TEST. Audio sounds a tad bit choppy on my end, I'm not sure what's causing it or if it's just my computer.

### CODE REVIEW

**Review by CaribbeanCool — CHANGES_REQUESTED** [review]
I'm getting this error when running on web:
image

Please if you merge main into your branch, it should resolve the problem

**Comment by gabrielpadilla7** [comment]
> @PinkSylvie @gabrielpadilla7 I'm getting this error when running on web:
> image
> 
> If you merge main into your branch, it should resolve the problem

Interesting.... Ill merge main onto the branch and push as soon as I can!

**Review by CaribbeanCool — APPROVED** [review]
Ya me corre y se escuchan los sonidos

**Comment by PinkSylvie** [comment]
Me corrio y se escuchan los sonidos. Adorable! Disculpas por la tardanza imageimage

Me salieron estos warnings but other than that everything looks and sounds great :D

**Review by PinkSylvie — APPROVED** [review]
If the screenshots I sent are no issue then it's all fine by me to merge. Again sorry for the tardiness

**Comment by gabrielpadilla7** [comment]
> Me corrio y se escuchan los sonidos. Adorable! Disculpas por la tardanza imageimage
> 
> Me salieron estos warnings but other than that everything looks and sounds great :D

the font thing is an error that sometimes happens with one of the pages. The other error there is an open issue to fix it at the moment.

**Comment by gabrielpadilla7** [comment]
Changes completed. Merging when checks are finished.

**Pull request merged**
