### PR TITLE
Usability Testing code added

### PR DESCRIPTION
**Pull request by FrHend-Raul**
Code to change, randomly, a page for testing. This code can be turned off by the programmer with a boolean variable added.

### CODE REVIEW

**Comment by PinkSylvie** [comment]
How does one test this? Is there a way to trigger the test or dies every time you the app the background random?

**Comment by PinkSylvie** [comment]
I see the boolean in the code, unsure of the implementation but it is technically a valid automation.

**Comment by FrHend-Raul** [comment]
The way the test works if to see how the user interaction changes on the different set for the page. If you can see the color change while running the app, then that is how it is supposed to work. The actual testing is to see how those changes affect the usability of the platform through user feedback. The user feedback was given when I gave the platform to some users and then asked them questions while they were testing the platform.

**Review by PinkSylvie — APPROVED** [review]
Hello! I ran it and saw the change, if you added your description of the usability test into the documentation with some pictures of what changes in each case, it should all be good to merge!

**Pull request merged**
