### PR TITLE
Added happiness update aspect to the minigame "game"

### PR DESCRIPTION
**Pull request by misaelmercado1**
Added happiness to update from the minigame , game.

### CODE REVIEW

**Comment by FrHend-Raul** [comment]
Ok, two issues here. One there is a merge conflict fix that. Second the font is not loading in the minigame. For this fix verify in the main branch because I had the issue in the bath minigame and its a simple fix adding a couple of code lines. @misaelmercado1

**Comment by misaelmercado1** [comment]
what font? Can u provide a screenshot because for me its working.

**Comment by FrHend-Raul** [comment]
image

When you enter the minigame without entering to any other page then that is the font presented, when it should be this one:

image

**Comment by misaelmercado1** [comment]
i resolved the merge conflicts,  do u know what would the cause for the font would be?

**Comment by FrHend-Raul** [comment]
The issue is that the page is being loaded before than the font is, you have to make sure to load the font and then load the page. Sent you the code needed by Discord.

**Comment by misaelmercado1** [comment]
Pls check i fixed font issue

**Review by FrHend-Raul — APPROVED** [review]
This code is ready for merge

**Comment by misaelmercado1** [comment]
branch up for checking with last cganges that were made to main

**Comment by PinkSylvie** [comment]
I still cant see the changes and now, the only image that shoes is the baby

**Comment by misaelmercado1** [comment]
wdym u cant see the changes and the image of the baby is not my fault check main it still displays a baby

**Comment by PinkSylvie** [comment]
I cant see the happiness change in the stats, it is always 100

**Comment by misaelmercado1** [comment]
the storage of the happiness follows the same logic with alejandros hapiness and hunger storage

**Comment by PinkSylvie** [comment]
I tried changing it via the hunger and happiness variable and it wont show. How can I know it increases the happiness if its always in 100%

**Comment by misaelmercado1** [comment]
Welp i dont know thats what i did based on what i was given. hunger and happiness may have the same problem with all the minigames because if the async storage. again not my implentetation.

**Pull request merged**
