### PR TITLE
Pet sleep schedule logic and restrictions.

### PR DESCRIPTION
**Pull request by FrancesC8**
Functionality:
* Added pet sleep schedule logic and storage.
* Interval function runs every minute to determine if the pet is sleeping or not.
* Added pet actions and stats restrictions when the pet is asleep.

Testing:
* Added and configured Jest for unit testing.
* Created tests for Pet sleep schedule feature.
* Generated code coverage report.
image

* Added and configured [Stryker](https://stryker-mutator.io/docs/) for mutation testing.
* Executed mutation tests and generated report with results (based on previously defined unit tests).
image

### CODE REVIEW

**Comment by FrancesC8** [comment]
@Negroni1 @irsaris @PinkSylvie This PR is ready for review, I can resolve the conflicts afterwards.

**Comment by PinkSylvie** [comment]
image
I tried running it but got this error

**Comment by FrancesC8** [comment]
@PinkSylvie that error is unrelated to my changes. Those images were somehow removed in previous commits and I sent out a message in the Discord channel pointing to this issue. If you want to test my changes, I suggest to comment out the lines that use those two jpeg files. FYI, to run unit test run `npm run test` and to run mutation tests `npx stryker run`.

**Comment by PinkSylvie** [comment]
The images were added again to main, I don't know why your branch doesn't have them. It's the only branch giving me this error

**Comment by FrancesC8** [comment]
Oh then, I just have to update my branch to master, I will do that in a few minutes. I have to update a part in the documentation to include the unit tests.

**Comment by FrancesC8** [comment]
@PinkSylvie resolved the merge conflicts and verified that the app is running on my machine

**Comment by PinkSylvie** [comment]
Pude correr el mutation test pero para el unit test me sale este error 
image

**Comment by FrancesC8** [comment]
I had to change the test script because it was conflicting with cucumber. To run the jest tests run `npm run test-jest`

**Comment by PinkSylvie** [comment]
I was trying to test the sleep restrictions but even if I changed the time and changed asleep to True, I could still play games and check the stats

**Comment by PinkSylvie** [comment]
image
Ran the unit test and they all failed

**Comment by PinkSylvie** [comment]
image

**Comment by FrancesC8** [comment]
@PinkSylvie All components that are dependent on the feature read the AsyncStorage for the source of truth at the beginning. Since the first part of the feature isn't done (#153) the feature is basically useless until the setInterval kicks in at the time the state of the Pet component to verify if the pet is asleep and update the AsyncStorage. If you want to test it, I suggest changing the return value of the method components/sleepScheduleStorage.js loadSleep() to `return 'true'`.

But I see that setInterval isn't working as expected. Let me take a look as it could be a bug, it was working before merging with main branch.

All the unit tests that I implemented are passing for me. Except the ones that depend on selenium webdriver. Which I assume I don't have the right configurations for it. Is there an extra step that needs to be done for the selenium based tests to pass? Was it passing for you before?

**Comment by FrancesC8** [comment]
Also, if the pet is asleep, do we need to block the stats page? Isn't the purpose of the stats page only show current stats of the pet regardless? I would assume that the user would be able to see it.

Also, any new code that has merged recently I haven't evaluated if it's actions need to be blocked if the pet is asleep, and I wouldn't get it all done in time. I can create a task to fix that bug for next milestone if that is okay

**Comment by FrancesC8** [comment]
I looked into the problem regarding changing the sleep time and it doesn't work.

If you changed the sleep time in the initial state of the Pet component, when calling the loadSleepScheduleFromStorage(), it will change the value to the default curfue which is '23:00' (11:00 pm). The part of the whole feature that is implemented assumes that the sleep time is in the AsyncStorage when the pet is created. Then the changes regarding the Pet sleep schedule feature in this PR would work as intended.

**Comment by FrancesC8** [comment]
When the pet is asleep, you should see the following in the home screen.
image

If any of the actions in the bottom of the home page are selected, an alert should show for all of them.
image

@PinkSylvie hope this helps!

**Comment by PinkSylvie** [comment]
Is there anyway for me to test this then?

**Comment by FrancesC8** [comment]
After a while with having the Sleep flag in the AsyncStorage set to true. The Pet component would run the setInterval for sleep and with the default value of sleep time '23:00' it will display the pet once more. Even tho the pet is not really awake yet. This behavior is expected for now, when #153 is done it should behave properly. 
image

**Comment by FrancesC8** [comment]
> If you want to test it, I suggest changing the return value of the method components/sleepScheduleStorage.js loadSleep() to `return 'true'`.

You can use this

"If you want to test it, I suggest changing the return value of the method components/sleepScheduleStorage.js loadSleep() to return 'true'."

**Comment by FrancesC8** [comment]
> Is there anyway for me to test this then?

If you want to test it, I suggest changing the return value of the method components/sleepScheduleStorage.js loadSleep() to return 'true' always.

**Comment by PinkSylvie** [comment]
image
I tried it out but it didnt let me test it

**Comment by PinkSylvie** [comment]
Nothing changed I mean

**Comment by FrancesC8** [comment]
The value should be a string 'true'

**Review by PinkSylvie — APPROVED** [review]
Finished testing, got to see the sleep feature and it works so nicely, amazing work! It is ready to merge

**Comment by FrancesC8** [comment]
Thanks for your help and patience!

**Pull request merged**
