### PR TITLE
Implement GUI tests from The Fuzzing Book

### LINKED ISSUE #132: [Lecture Topic Task] Implement in project from The Fuzzing Book
This was material the professor assigned the days there were not any class. If it's coding make sure to put it in the project code as well as document it in the Milestone doc. If it's just documentation, make sure it is well done in the Milestone doc.

"https://www.fuzzingbook.org/html/00_Table_of_Contents.html
your task is to proceed to the chapter on "Testing Graphical User Interfaces". This means to will have to work through the chapters leading up the this chapter. Then apply the tools of these chapters to your project."

### PR DESCRIPTION
**Pull request by ghost**
## Changes
Implement the graphical user interface tests from [_The Fuzzing Book_](https://www.fuzzingbook.org/html/GUIFuzzer.html#) as per issue #132 and the professor's request in order to make up for canceled classes.

### Documentation
Documentation was added to section _4.1 TDD_

## Frameworks
These tests use [Jest](https://jestjs.io/) and [Selenium](https://www.selenium.dev/) testing frameworks in order to carry the tests out.

## Tests Implemented
The flashcards page and the eat page are getting fully tested. For the flashcards page, we ensure navigation to it from the home page is possible, we ensure that we can add a flashcard, and we ensure that we can remove a flashcard. For the eat page, we ensure navigation to it from the home page is possible, and we make sure that we can pass the minigame with the appropriate result. Three different tests for the minigame have been implemented, one that is supposed to pass with 0/5, another 3/5, and the last one 5/5. For each one, we ensure that the resulting hunger and happiness result is as expected.

## How to run the tests
To run the tests, you need to have the expo server running in the background (`npx expo start`), and, in another terminal, you run the tests by executing `npx jest`.

### CODE REVIEW

**Review by irsaris — APPROVED** [review]

**Comment by PinkSylvie** [comment]
I tried running it but Visual Studio was having a conniption trying to run the tests. How do I know if the tests succeded? I have only seen when the test fail that is when I have to stop the server

**Comment by diego-velez-upr** [comment]
> I tried running it but Visual Studio was having a conniption trying to run the tests. How do I know if the tests succeded? I have only seen when the test fail that is when I have to stop the server

Well, when you run the `npx jest` command, it should tell you if it succeeded or failed. When you do that you will see a browser open, per test one at a time, and you should be able to see it go through the application (it's pretty fast though).

So, for example, this is what I see after the tests finish:
image


Also, just so you know, I don't think you even need any IDE open tbh, you could open a terminal, navigate to project and run the commands there. Might be useful if VS Code is too buggy lmao

**Comment by PinkSylvie** [comment]
image
This is what I got when I tried to run it as you said

**Comment by diego-velez-upr** [comment]
> image
> This is what I got when I tried to run it as you said

Huh, weird, I'm not getting that at all.

The tests are using Firefox, do you have it installed?

**Comment by PinkSylvie** [comment]
Yes I have Firefox

**Comment by diego-velez-upr** [comment]
@PinkSylvie can you run it again and send me the errors it show? to see if I can replicate them, because the tests are working for me

**Comment by PinkSylvie** [comment]
@diego-velez-upr This is the error I'm getting now 
image

**Comment by diego-velez-upr** [comment]
@PinkSylvie can you update and check if it works for you now? I realized I hadn't added the Jest config.

**Comment by PinkSylvie** [comment]
image
I tried it and got this error

**Comment by diego-velez-upr** [comment]
@PinkSylvie Are you sure that you are running the expo server in the background before running the tests? Also, you might need to refresh the project (`npm install`) when switching branches.

**Comment by PinkSylvie** [comment]
Yes and yes I did both

**Comment by gabrielpadilla7** [comment]
image

Ran tests, installed the necessary dependancies to run them and they all passed! However there are merge conflicts that must be resolved before anything. Please resolve them beforehand.

**Review by gabrielpadilla7 — APPROVED** [review]
Tests passed, check merge conflicts and once fixed, merge can be done

**Pull request merged**
