### PR TITLE
Set up snapshot test on Pet Shop component

### LINKED ISSUE #102: [Lecture Topic Task] Snapshot testing on Pet Shop
Implement snapshot testing into Pet Shop component

"Snapshot testing is a type of output comparison testing. This type of testing ensures that your application adheres to the quality characteristics and code values of your development team. Snapshot tests are useful when you want to make sure your UI does not change unexpectedly." [Source](https://circleci.com/blog/snapshot-testing-with-jest/#:~:text=Snapshot%20testing%20is%20a%20type,UI%20does%20not%20change%20unexpectedly.)

### PR DESCRIPTION
**Pull request by joel-alvarado**
closes #102

### CODE REVIEW

**Comment by PinkSylvie** [comment]
How do I run this?

**Comment by joel-alvarado** [comment]
> How do I run this?

Same as any regular jest test (npx jest filename)

**Comment by PinkSylvie** [comment]
Which filename for this?

**Comment by joel-alvarado** [comment]
> Which filename for this?

If you are in root directory, you can use `npx jest ./__tests__/PetShopSnapshot.test.js` to run it.

**Review by PinkSylvie — APPROVED** [review]
Ran perfectly! Great work!

**Comment by PinkSylvie** [comment]
Merge asap

**Pull request merged**
