### PR TITLE
Database setup (MUST READ BEFORE APPROVING OR REVIEWING)

### LINKED ISSUE #242: Set Up DB
Set up Database, this must at least be able to store User Data as well as other data  of the application. 

More details to come 

Difficulty: Max
Priority: Max (2 week constraint from milestone start)

### PR DESCRIPTION
**Pull request by gabrielpadilla7**
Database has been set up using realm.js. Closes #242 #244  AND #314 as the testers for the DB are initialized and done. If more testing needs to be done let us know. 

HOWEVER, some testers are broken. This happened when I merged the main branch onto my branch, meaning that somewhere along the way, those testers broke. 

One test (studypet.test.js) was modified, as it was expecting FIREFOX as a browser and it should work with any browser. Eat tests ALSO FAIL due to the fact that it has not been updated and the Pet is constantly in the FULL state, causing these tests to not work.

### CODE REVIEW

**Comment by gabrielpadilla7** [comment]
Added aditional testers, now closes additional issue. @irsaris please add the issue to the project board.

**Comment by irsaris** [comment]
> Added aditional testers, now closes additional issue. @irsaris please add the issue to the project board.

PR themselves are not added to the Project Board.

**Comment by gabrielpadilla7** [comment]
> > Added aditional testers, now closes additional issue. @irsaris please add the issue to the project board.
> 
> PR themselves are not added to the Project Board.

I meant the new issue that was added to add more testers, issue #314

**Comment by irsaris** [comment]
> > > Added aditional testers, now closes additional issue. @irsaris please add the issue to the project board.
> > 
> > 
> > PR themselves are not added to the Project Board.
> 
> I meant the new issue that was added to add more testers, issue #314

This issue was already added to the board though.

**Review by PinkSylvie — APPROVED** [review]
Everything looks great! As soon as you fix the conflicts you can merge

**Comment by gabrielpadilla7** [comment]
Conflicts have been resolved, once checks are done merging will be done

**Pull request merged**
