### PR TITLE
added aditional tests to the file

### PR DESCRIPTION
**Pull request by CaribbeanCool**
I took the eat page test that was made by @diego-velez-upr, and since it had only 1 test, I added other tests and refactored the code

### CODE REVIEW

**Comment by diego-velez-upr** [comment]
The changes seem fine, but can we get @gabrielpadilla7 to test them out and approve? since I'm not at my PC anymore, if he approves then its fine by me

**Comment by gabrielpadilla7** [comment]
Checking right now

**Review by gabrielpadilla7 — CHANGES_REQUESTED** [review]
image

Changes need to be made. Two tests fail, the eat page (plays the minigame) and the eat page (passes minigame with 0/5). Both of these tests fail with the NoSuchElementError: Unable to locate element

**Comment by gabrielpadilla7** [comment]
@CaribbeanCool Any updates on this PR?

**Comment by CaribbeanCool** [comment]
> @CaribbeanCool Any updates on this PR?

My bad. The last two fail since the pets hunger is full. The tests work based on the web app specifically. This means that the tests don't bypass certain things, like the pet's stats

**Comment by gabrielpadilla7** [comment]
@CaribbeanCool I see, so the tests will always fail or does it need to be in another environment in order for them to pass?

**Comment by CaribbeanCool** [comment]
> @CaribbeanCool I see, so the tests will always fail or does it need to be in another environment in order for them to pass?

@gabrielpadilla7 It doesn't need to be in another environment. The test will fail if the pets hunger is above 10. For example, if you change the pet's hunger to 11 in `Pet.jsx`, the message "You are full!" will disappear, and the minigame would be available, meaning that the test fails when you run it.

**Comment by diego-velez-upr** [comment]
Is there a way that you could change the hunger before the tests run, so that way the tests pass successfully?

I don't think it'd be a good idea to submit the tests if they fail everytime.

**Comment by PinkSylvie** [comment]
We could change the default instead of 0 to a higher amount. I think in Pet.jsx?

**Comment by CaribbeanCool** [comment]
@PinkSylvie Since I haven't found a way to change the hunger in the tester itself, and Diego wants the tester to run without tests failing, do I remove the full test?

**Comment by PinkSylvie** [comment]
I dont think you need to change the hunger in the tester, but in the default pet the hunger could be changed

**Comment by CaribbeanCool** [comment]
> I dont think you need to change the hunger in the tester, but in the default pet the hunger could be changed

But if you change the hunger, either one test fails or two test fail

**Comment by diego-velez-upr** [comment]
> I dont think you need to change the hunger in the tester, but in the default pet the hunger could be changed

I think normally you want to change the test to fit the production code instead of the other way around, but if it isn't a big deal, doesn't break components or mess with the intended workflow of the app, then it might be fine.

Either way, I think that we shouldn't submit failing tests.

**Comment by PinkSylvie** [comment]
It might be for the best to delete them then

**Comment by CaribbeanCool** [comment]
> It might be for the best to delete them then

The tests themselves or simply the full one?

**Comment by PinkSylvie** [comment]
The tests themselves, we don't want to submit failing tests

**Comment by CaribbeanCool** [comment]
@PinkSylvie Ok. Can i close the PR then?

**Comment by PinkSylvie** [comment]
Yes

**Pull request closed without merging**
