### PR TITLE
Eat minigame availability

### LINKED ISSUE #300: Implement unavailability of `Eat` Page when pet is not hungry
### Points
- Difficulty: 4
- Priority: 3

### PR DESCRIPTION
**Pull request by CaribbeanCool**
Added functionality of user not having access to Eat minigame when not hungry
close #300
image

### CODE REVIEW

**Comment by CaribbeanCool** [comment]
The condition for this exact page to show up is when the hunger is below or equal to ten

**Review by gabrielpadilla7 — CHANGES_REQUESTED** [review]
image
This warning of the fonts appear when going to the eat screen

image
The eat screen on mobile looks like this, unfortunately the text gets cut off. 

Also, no matter what value of hunger that I put in the Pet.jsx, the screen stays the same and always says that the pet is full (the pet DOES work with the hunger as the animation of the pet changes with the hunger value)

**Comment by CaribbeanCool** [comment]
@gabrielpadilla7 This is the photo when I run it on Expo Go:
WhatsApp Image 2024-04-01 at 23 27 10_e2843c9e

Right now I don't know how to trespass the pet being asleep, and I cant feed the pet

**Comment by CaribbeanCool** [comment]
@gabrielpadilla7 @PinkSylvie

**Comment by PinkSylvie** [comment]
It's giving me this warning. But other than that it runs nicely, I changed the hunger to see how it allowed you access when the hunger was above 0 and didn't allow the pet to eat when it wasn't. Other than this tiny detail it looks great, Good workimage

**Review by PinkSylvie — APPROVED** [review]
Great work!

**Comment by CaribbeanCool** [comment]
@PinkSylvie I put a conditional (can be changed) that when the hunger goes above 10, then you can eat. I changed it to `11` and it let me play

image
__________________________________________________________________________________________________________________________________________
image

**Comment by PinkSylvie** [comment]
Don't worry I was able to play and test it despite the warnings. Just don't think is a good idea to merge it with those warnings going boj

**Comment by CaribbeanCool** [comment]
> Don't worry I was able to play and test it despite the warnings. Just don't think is a good idea to merge it with those warnings going on

I tried verifying the warning, and it is about `status` in line 51 of `HomePage.js`, meaning that it comes from the person who implemented notifications

**Comment by CaribbeanCool** [comment]
@PinkSylvie I think I fixed the warning. Let me know 👍

**Comment by CaribbeanCool** [comment]
Can I merge?

**Comment by PinkSylvie** [comment]
Looks ready to merge!

**Pull request merged**
