### PR TITLE
Added Mutation Testing for the Fuzzy Test

### PR DESCRIPTION
**Pull request by AnthonyMed13**
For this task I added mutation testing with stryker for the Fuzzy test. This can be run with the command npx stryker run. This code right now fails the fuzzy test cases since the fuzzy test has not been updated to the newest home layout . If im not mistalen they are currently working on a fix for this from what I saw on discord general chat. So for now this is the expected output.

mutation1
mutation2

### CODE REVIEW

**Comment by PinkSylvie** [comment]
Please update us as soon as it runs properly so it can be reviewed and approved

**Comment by gabrielpadilla7** [comment]
@AnthonyMed13 Any updates on the code?

**Comment by AnthonyMed13** [comment]
> @AnthonyMed13 Any updates on the code?

I have the updated version since @diego-velez-upr is the one updating the Fuzzy Test and he sent me the branch I confirmed that the code works now I am waiting on him to do a pull request on his branch so I can do mine

**Comment by gabrielpadilla7** [comment]
> > @AnthonyMed13 Any updates on the code?
> 
> I have the updated version since @diego-velez-upr is the one updating the Fuzzy Test and he sent me the branch I confirmed that the code works now I am waiting on him to do a pull request on his branch so I can do mine

Understood, I just approved I think that PR so that PR is ready to merge (if it has conflicts then fix and merge would be done)

**Review by PinkSylvie — APPROVED** [review]

**Pull request closed without merging**
