### PR TITLE
After pet creation study set creation

### PR DESCRIPTION
**Pull request by JeremySanchez1**
Automaitically navigates to new study set creation page right after pet creation, created flash cards are then sown in the flashcards overview section

image

image

### CODE REVIEW

**Review by irsaris — APPROVED** [review]
Good work, check to see if there's any conflicts before merging.

**Review by CaribbeanCool — CHANGES_REQUESTED** [review]
When I create a pet, it sends me to `Create study set`, but the page is white and I can't do anything. Plus, resolve conflicts.

image

**Comment by PinkSylvie** [comment]
You have until today to fix the bug and conflicts and merge this

**Comment by JeremySanchez1** [comment]
image

image


I'm not seeing a problem on either the website or the Android emulator. Could someone else verify the workings of the feature to see if it's a local device problem? @PinkSylvie @CaribbeanCool @gabrielpadilla7 @irsaris @Mark-Anton

**Review by PinkSylvie — APPROVED** [review]
It worked for me, but I have an issue that we have to fix for next milestone. We need to add a button for the flashcard screen to jump home because when I press back it literally goes back to all the screens ran. But it looks great!

**Pull request merged**
