### PR TITLE
Implemented pet stages

### PR DESCRIPTION
**Pull request by JonathanDebug**
Pet stages is implemented, the pet will now need a creation date, exam date and the current day in which the aging of the pet will be based on. Every 1/3 of the days leading to the exam, the pet will grow one level until level 3 in which it will stop growing. For full completion, I need the pet creation to be done completely and in working order since when a pet is created, nothing happens, for now, dummy dates has been added to the constructor. Ps. dates have need to be in this format to work with Date()  yyyy-mm-dd

### CODE REVIEW

**Comment by PinkSylvie** [comment]
Hello! I tried it out and I saw the growth level change but not the pet's image. And the dates you assigned aren't reflected in the pet's stats

**Comment by JonathanDebug** [comment]
Hello, the pet images should change to different moods, since Im not in charge of pet designs and all that I do not have the stages (baby,young and adult pictures)  that are supposed to, but the images does change from my part just for testing i used the different moods that the pet has (sad, happy,...). I did not understand what you meant when you said the dates do not reflect?

**Comment by PinkSylvie** [comment]
In the exam date on the stat another date appears that isn't the exam date you gave for testing, it says the exam date is 2024-02-22. And you are correct that the change is reflected now, tho it oddly jumps from stage 0 to stage 3.  And part of the pet stages is the images, which I recommend for you to speak with @Negroni1 so you can get the correct ones.

**Comment by JonathanDebug** [comment]
I saw that too, it appears its part of calculating the level and it does it on intervals, right now I think is set to 3 seconds, i could change it to a faster interval, see if it works, ill talk to the person in charge of the design.

**Comment by JonathanDebug** [comment]
I added the new pet images, they are not animations since I think they arent done but now you can see the change in stages, also  I changed the response time on the level calculation and it should be faster by automatically showing the level that it is. @PinkSylvie

**Review by Negroni1 — APPROVED** [review]

**Review by CaribbeanCool — DISMISSED** [review]
Se ve bien, pero tiene conflicts con `main`, soo resuelvelos y se podria merge

**Comment by JonathanDebug** [comment]
The changes are done. @CaribbeanCool

**Comment by PinkSylvie** [comment]
The change was so quick, I could only see the frog egg and the adult stage. And that's odd it did that jump since the start and exam days are days apart

**Comment by JonathanDebug** [comment]
The user its not supposed to see the stages in real time, just depending on the day the pet will be a defined stage, i cannot do anything about the loading since the program takes time calculating the level and changing the picture. If you wish to see the different stages, you have to change the dates that are inside the constructor since they are outdated, thats why it shows the adult stage.

**Comment by PinkSylvie** [comment]
I saw the egg and adult stage without doing anything. That's what I'm concerned about

**Comment by JonathanDebug** [comment]
Yes, since the dates in the constructor are outdated, the exam has already passed, meaning that the max stage a pet will have is level 3 (adult), but since the default stage is 1 (baby) it will start as a baby but then calculate the level depending on your current date, and then updating it to an adult, that is what you are seeing.

**Comment by PinkSylvie** [comment]
I don't think that'd be a good thing to happen every time the app is opened

**Comment by JonathanDebug** [comment]
Perhaps would be better to not show anything before the level is calculated? Would that suffice?

**Comment by PinkSylvie** [comment]
Why is the default the baby stage? Does it calculate the level every time the app opens? Might be for the best for now to do your suggestion, but when data sync is implemented it needs further polish

**Comment by JonathanDebug** [comment]
The constructor has a default level of 1, not by choice but a pet cannot have None as a level, also since pet creation does not currently work, I have to work with what I have and that is the pet constructor. I can implement so that a pet would start at level 0 so it does not show anything until the level has been calculated. But until pet creation is not implemented completely I cannot work with the data from it since it does not exist. For now, pet stages is proven to work but ofcourse it needs adjustments that can be worked on the next milestone.

**Comment by PinkSylvie** [comment]
We don't want it to be at 0 for the totality of the presentation. Especially with new implemented pet varieties that dont have their other stages implemented yet. I think it'd be best for the default to be the adult. Then dates can be changed to see the other stages

**Comment by JonathanDebug** [comment]
Default level has been set to 3 (Adult).

**Comment by PinkSylvie** [comment]
Estaba probandolo y parece estar atascado en un loop infinito cuando probe cambiar las fechas y no me dejaba cambiar de pagina. Pude ver el baby stage pero again didnt let me do anything else

**Comment by JonathanDebug** [comment]
Thats odd, it works fine from my end.

**Comment by PinkSylvie** [comment]
Also the branch has conflicts now with Pet

**Comment by PinkSylvie** [comment]
Just tested it and it works, please fix the conflicts with pet so I can approve and merge

**Comment by JonathanDebug** [comment]
conflict resolved.

**Comment by PinkSylvie** [comment]
Does this merge have the pet stages images? If it does we could merge this with main to add them back and that way solve the issue notification has

**Comment by JonathanDebug** [comment]
Close the issue related to the PR when done.

**Review by PinkSylvie — APPROVED** [review]
Tested it out and it works well! Great work! Gonna merge and close

**Pull request merged**
