### PR TITLE
PlayerStats

### PR DESCRIPTION
**Pull request by Mark-Anton**
created playerStats.js created counters to be later changed.

### CODE REVIEW

**Review by irsaris — APPROVED** [review]

**Comment by PinkSylvie** [comment]
This page has conflicts

**Comment by PinkSylvie** [comment]
Please fix them

**Comment by PinkSylvie** [comment]
You have until today to fix the conflicts and merge this

**Comment by PinkSylvie** [comment]
Please fix the conflicts here too

**Pull request merged**
