### PR TITLE
implemented animation changes depending on happiness and hunger stats

### PR DESCRIPTION
**Pull request by benjaminCMD**
This pull is related towards issue #182 and #177. I was able to make changes in the animation depending on its stats: hunger and happiness. Right now the priority is hunger, then happiness. When hungry is 50 or higher, the pet becomes angrier. Once the hunger is lower than 50, then it changes to the animation where happiness is involved. The pet's happiness has different changes
 100-80 (happy), 40-79(regular animated frog), 39-0 is sad animation. All of this was done in Pet.jsx
Screenshot 2024-03-20 195938

For me to test if it worked, I hardcoded the values inside the pet, since I have no control over the happiness or hunger. Mess around with the different ranges between happiness and hunger, and see if it is towards your liking
Screenshot 2024-03-20 202632

### CODE REVIEW

**Review by irsaris — APPROVED** [review]

**Comment by PinkSylvie** [comment]
Please fix the conflicts @gabrielpadilla7

**Comment by gabrielpadilla7** [comment]
On it

**Comment by PinkSylvie** [comment]
image
Hunger and Happiness isnt reflected in the stats, so I cant see any changing animation

**Comment by gabrielpadilla7** [comment]
Right now I've been caught up in other work, if someone could help me in fixing the conflicts that would be greatly appreciated!

**Comment by benjaminCMD** [comment]
I'm gonna create a new branch to make a pull request, because the base code for pet.jsx I used was very outdated

**Comment by PinkSylvie** [comment]
I tried to test it as you say by hardcoding and the changes arent shown

**Comment by benjaminCMD** [comment]
Okay, right now, me and @PurpleDerg are in another branch called pet-emotions, since changes-in-animation- is a branch with outdated code that's no longer usable. What we have noticed is that Happiness stays at 100 and the growth-level is always at 1 no matter how much I hardcode the values inside the constructor and we havent found to access either of them. Hence, I cant make any changes in animations without fixing this issue first.

**Comment by benjaminCMD** [comment]
Okay, so I found the issue. Apparently async storage is apparently buggy for happiness and that why it wasnt functioning properly. I commented out this.loadHappinessFromStorage(), this.loadHungerFromStorage() from the pet.jsx and now I am able to manipulate happiness directly from the constructor. However, growth level is still buggy and always set 1, so I basically hardcoded so that only renders changes in animation as an adult at growth level 1

**Comment by PinkSylvie** [comment]
Did you push those changes to your branch?

**Comment by benjaminCMD** [comment]
Not yet, I'm adding comments to explain my changes, then I'm gonna push into the branch

**Comment by PinkSylvie** [comment]
You already have a pull request that is further up ahead than this one related to this issue so I'm gonna close this one to avoid cluttering the pull request board

**Pull request closed without merging**
