### PR TITLE
`eat` tests

### LINKED ISSUE #305: [Lecture Topic Task] Restore Tests for `Eat` Minigame to previous state
Restore eat tests to previous state and make sure that merges done after this one aren't lost. 

Points:
- Difficulty: 4
- Priority: 4

### PR DESCRIPTION
**Pull request by CaribbeanCool**
## Description
This is a test file for the `Eat` page and minigame

close #305

### CODE REVIEW

**Comment by PinkSylvie** [comment]
Hello! I'd like to run the tests, can you explain how are they supposed to turn out? Tho in previous experience my computer couldn't handle well BDD tests

**Comment by CaribbeanCool** [comment]
@PinkSylvie There are 4 tests:
1. The test navigates to the eat page properly -> should run perfectly
2. The test makes sure that the page displays `you are full!` -> should run when the hunger is above 10
3. The test for making sure that the minigame is playable -> should run normally; depends on the pet's hunger being above 10
4. the test for getting 0/5 in the minigame -> also should run normally; depends on the pet's hunger being above 10

**Review by gabrielpadilla7 — COMMENTED** [review]
image

Currently running into this problem. Not sure if there is a problem with the code or if there is something I would need to do on my end

**Comment by CaribbeanCool** [comment]
@gabrielpadilla7 in `eatPage.test.js`, there is a variable called `port` where you can change it to the port expo gives you for web
image

**Review by gabrielpadilla7 — CHANGES_REQUESTED** [review]
Tests still fail on my end. X path is I believe the least reliable way to test as I believe it changes with the screen resolution. There's a few other ways to scan for elements, see if you can modify it for that, otherwise try to find a way for it to work on all computers. Thank you!

**Review by gabrielpadilla7 — CHANGES_REQUESTED** [review]
It still doesn't work on my end. Can someone else test this and let me know if it's just on my end or if it's an issue on some computers?

**Comment by gabrielpadilla7** [comment]
> It still doesn't work on my end. Can someone else test this and let me know if it's just on my end or if it's an issue on some computers?

@irsaris @joel-alvarado @PinkSylvie @Fabian-J @JorgeC08

**Comment by FrHend-Raul** [comment]
A mi al menos me corrio

image

En este run, corrio con el hunger full, so no pudo jugar el minigame (eso son los fails que son de esperar).

image

En este run, corrio con el hunger a 30, en ese el unico fail fue que no vio el Hunger full! screen lo cual era de esperar y se vio que en la anterior corrida trabajo como se supone.

**Comment by CaribbeanCool** [comment]
@PinkSylvie Can i merge?

**Comment by PinkSylvie** [comment]
Sorry for taking a bit, how do I run the tests?

**Comment by PinkSylvie** [comment]
Got these errors when running. The 5000 could an issue my laptop has with the tests. 
image
But these are new that I didnt get when I ran similar tests for others tasks: 
image
image

**Comment by CaribbeanCool** [comment]
@PinkSylvie I only made `eatPage.test.js`. The other tests are from different people. If I'm not wrong, `studypet.test.js` was made during the beginning of Milestone 2, meaning that the person hasn't updated the tests. When the 5000 appears, run the test again.

**Comment by PinkSylvie** [comment]
I've ran several recent tests made for this milestone and the past one and have had the same 5000 error appear for any that have pop ups

**Comment by CaribbeanCool** [comment]
@PinkSylvie I added more time to the timeout if that works. With that to the side, I think it's ready to merge

**Comment by PinkSylvie** [comment]
image
It should be since others were able to run it and it seems to be an issue with my device not with the code except with this, which concerns me since it is also related to the eat tests.

**Comment by CaribbeanCool** [comment]
That error is very weird

**Review by CaribbeanCool — COMMENTED** [review]
.

**Review by PinkSylvie — APPROVED** [review]
It runs on others devices, the issue seems to be exclusive on mine so it should be good to go

**Pull request merged**
