### PR TITLE
change difficulty settings

### PR DESCRIPTION
**Pull request by bally7301**
change to decide the dificulty of the minigames in from directly in them to when you creat a pet

### CODE REVIEW

**Comment by irsaris** [comment]
did you create another PR for the same task?

**Comment by PinkSylvie** [comment]
I ran it and it ran nicely! Whenever you fix the minigame test errors and the conflicts it should be ready to merge!

**Review by PinkSylvie — APPROVED** [review]
Looks ready to go! Fix the conflicts first tho

**Comment by gabrielpadilla7** [comment]
@PinkSylvie For some reason one of the automatic test runners is not working after the main was merged into difficulty_added (110f752). You can see it becasue of the Xs in the commits

**Comment by PinkSylvie** [comment]
I've seen that, its the only branch which this has happened with

**Pull request closed without merging**
