### PR TITLE
Implement notifications

### PR DESCRIPTION
**Pull request by JonathanDebug**
Notifications have been added. Now a notification can be added for any type of scenario. When the app is launched, the user is asked for permission to allow notifications. Then a new optional (can be deleted) button has been added to test the notifications, the user will get a notification once the button is pressed, this has been done only for testing and debugging purposes. Also the user will receive a notification asking them to come back and study when the app is on the background.

### CODE REVIEW

**Comment by PinkSylvie** [comment]
How can I test this?

**Comment by JonathanDebug** [comment]
Theres a button that lets gives u a notification each time you press it. Also if you exit the app, a notification should pop up, im using the emulator in android studio.

**Comment by JonathanDebug** [comment]
Clarification for anyone testing the feature: YOU NEED TO USE ANDROID STUDIO AND HAVE AN ANDROID EMULATOR OR DEVICE. Notifications do not work on web, permissions are needed that are asked via an android device.

**Comment by PinkSylvie** [comment]
Do they work on iPhone?

**Comment by JonathanDebug** [comment]
Since I dont own a Mac, there is no way for me to know, testing on an Iphone only works on mac.

**Comment by PinkSylvie** [comment]
Just tested it on iPhone and it worked perfectly! For now this great for this milestone! I think there some things that could be done for next milestone including setting that the notification permission is opened when you first open the app and to give it permissions in the settings screen instead of via button :) I think it's fine to merge

**Review by PinkSylvie — APPROVED** [review]
Looks great! I say you can merge it already!

**Comment by JonathanDebug** [comment]
For sure! Ill make sure to make it a task for the next milestone and work on it, thanks!

**Review by irsaris — APPROVED** [review]

**Comment by PinkSylvie** [comment]
Please fix the conflicts so the task can be merged

**Comment by JonathanDebug** [comment]
Conflict resolved.

**Comment by PinkSylvie** [comment]
image
Me esta dando este error ahora

**Comment by JonathanDebug** [comment]
Someone is deleting the pictures for the stages.

**Comment by PinkSylvie** [comment]
Could you please add those images back again with the name used in the pets image array? Your task is already done and it would be the next one to be merged. This is holding it back.

**Comment by JonathanDebug** [comment]
Done

**Comment by JonathanDebug** [comment]
Close the issue related to this PR when done.

**Comment by PinkSylvie** [comment]
This has conflicts again, please fix @JonathanDebug

**Comment by PinkSylvie** [comment]
image
Me esta dando este error cuando lo intento correr

**Comment by PinkSylvie** [comment]
@JonathanDebug

**Comment by JonathanDebug** [comment]
Hi, there is a easy fix for one of the conflicts but for the other is a .json file that i have not messed with that have a lot of conflicts and its a very large file, it seems to be from some sort of dependency, is there a more secure way to fix it? i do not know of these packages and what problems may cause if i edit them.

**Comment by JonathanDebug** [comment]
check if it works now @PinkSylvie

**Comment by PinkSylvie** [comment]
No bugs, works perfectly! Please fix the conflicts to be able to merge it

**Comment by JonathanDebug** [comment]
im having trouble getting rid of the conflicts in the .json file, this file has 100k+ lines of code, when i fix them it dont let me check it as fixed, and that prevents me on fixing this issue.

**Comment by PinkSylvie** [comment]
Have you tried after fixing it erasing the red boxes that surround the conflicts?

**Comment by JonathanDebug** [comment]
Yes thats literally what im doing. I want to leave all the code and have deleted all the lines that indicate the conflict.

**Comment by JonathanDebug** [comment]
would it be possible to delete the file and when the merging occurs then the file that is working should be added?

**Comment by PinkSylvie** [comment]
Maybe deleting the json file would work. You'd just have to install the dependencies again and make sure it runs properly in main asap. We already have enough bugs in main as is

**Comment by JonathanDebug** [comment]
Merge problems solved.

**Comment by JonathanDebug** [comment]
@PinkSylvie

**Comment by PinkSylvie** [comment]
Please fix the conflicts so you can finally merge your branch, you have till today to have your branch merged

**Comment by JonathanDebug** [comment]
Wait i thought I did this on Thursday.

**Comment by JonathanDebug** [comment]
@PinkSylvie im currently driving to mayaguez, i thought i had solved all these problems on thursday and I didnt see this, I will fix them as soon as i get there, aprox like an hour.

**Comment by JonathanDebug** [comment]
Hi i stopped and tried to fix it, please check if its works.

**Comment by PinkSylvie** [comment]
Sorry for taking so long, me han estado saliendo varios errores intentando correrlo 
image

**Comment by JonathanDebug** [comment]
Does this error appear from the notifications branch?? To see if i can fix it.

**Comment by PinkSylvie** [comment]
Yes

**Comment by JonathanDebug** [comment]
i am getting errors from other files that i have not changed.

**Comment by PinkSylvie** [comment]
Maybe they are files that got merged into main that are now conflicting with yours

**Comment by JonathanDebug** [comment]
i dont know what to do, im getting this error now : Android Bundled 5825ms (C:\Users\jonat\Desktop\StudyPet\semester-project-study-pet\node_modules\expo\AppEntry.js)
 ERROR  ReferenceError: Property 'MyPetScreen' doesn't exist, js engine: hermes
 ERROR  Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes
*

**Comment by JonathanDebug** [comment]
have u gotten this error because of internet connection? i have not arrived to mayaguez and im currently in a gas station trying to fix this so my internet connection is not the best.

**Comment by PinkSylvie** [comment]
No, when it is because of internet connection I get other errors

**Comment by PinkSylvie** [comment]
image
I was reading the errors and it seems that there are double the things and the conflicts weren't fixed properly

**Comment by JonathanDebug** [comment]
yeah i fixed those already, the error is in another file that i have not worked with.

**Comment by PinkSylvie** [comment]
image

**Comment by PinkSylvie** [comment]
image
I think ypu have something double here too, I think again you did the commit conflicts fix wrong, you just deleted the red blockers instead of checking if there was any doubles

**Comment by JonathanDebug** [comment]
those errors have already been corrected, try and pull, there is still the error and now probably there is going to be more conflicts.

**Comment by JonathanDebug** [comment]
Now you will be able to see the error that im getting.

**Comment by JonathanDebug** [comment]
image

**Comment by PinkSylvie** [comment]
Que tal si le das de reversa a tu branch a un punto en donde aun funcionaba y luego lidias con los conflicts otra vez

**Comment by JonathanDebug** [comment]
How can i do that? I was trying but no success.

**Comment by JonathanDebug** [comment]
Fixed errors on a new branch, will now proceed to make a new PR with the new branch, i will comment the link here. 
image_2024-03-25_013837881

**Comment by PinkSylvie** [comment]
That's great! I'll close this branch then and keep an eye for the new PR to test it approve it and merge it

**Comment by JonathanDebug** [comment]
https://github.com/uprm-inso4117-2023-2024-s2/semester-project-study-pet/pull/282

**Pull request closed without merging**
