### PR TITLE
Flashcards functionalities

### PR DESCRIPTION
**Pull request by williammartinez10**
# Description
This branch holds the work done for #142 , #143 and #196 in the flashcards page. It allows displaying a flashcard remover component on screen, along with the actual ability to create and remove flashcards.

### CODE REVIEW

**Comment by PinkSylvie** [comment]
Tried to run it but got this error 
image

**Comment by williammartinez10** [comment]
I believe they need to be installed individually.

- ```npm install @react-native-async-storage/async-storage```
- ```npm install react-native-gesture-handler```
- ```npm install react-native-safe-area-context ```

I got the same errors regarding the gesture-handler and safe-area-context past milestone, and when i first started working on my tasks, but this solved it. Not entirely sure why those errors keep popping up.

**Comment by CaribbeanCool** [comment]
@PinkSylvie @irsaris Me corrio el branch, tuve que correr `npm install`.

image

image

image

**Review by irsaris — APPROVED** [review]

**Review by CaribbeanCool — APPROVED** [review]
LGTM👍

**Comment by PinkSylvie** [comment]
image
Sorry que no haya respondido, he intentado correr el branch varias veces pero me siguen saliendo errores con expo, npm y metro cache

**Comment by PinkSylvie** [comment]
@williammartinez10

**Comment by williammartinez10** [comment]
Try `npx expo start`

**Comment by PinkSylvie** [comment]
Eso funciono! Como que se deberia cambiar el read me paar que en vez de que diga expo start diga npx expo start

**Comment by PinkSylvie** [comment]
I ran it but I'm getting a blank screen in the flashcard screen. Everything else looks fine. @williammartinez10

**Review by PinkSylvie — APPROVED** [review]
Finally loaded, it took its sweet time but the flashcard overview loaded, I tried it out and I think it looks great and everything works nicely. I think its good to merge and close. And again sorry for taking so long to approve

**Comment by PinkSylvie** [comment]
Just @ me and/or irsaris and we'll close all of the tasks related to this pull request

**Pull request merged**
